"""create products and product_changes

Revision ID: 58085105cd6f
Revises:
Create Date: 2026-09-28 22:15:23.459245

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "58085105cd6f"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("product_id", sa.BigInteger(), nullable=True),
        sa.Column("sku", sa.Text(), nullable=True),
        sa.Column("partner_sku", sa.Text(), nullable=False),
        sa.Column("product_name", sa.Text(), nullable=True),
        sa.Column("asset_type", sa.Text(), nullable=True),
        sa.Column("has_serial", sa.Boolean(), nullable=True),
        sa.Column("has_expiration", sa.Boolean(), nullable=True),
        sa.Column("color", sa.Text(), nullable=True),
        sa.Column("size", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column(
            "units",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "categories",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("fingerprint", sa.LargeBinary(), nullable=False),
        sa.Column("version", sa.Integer(), server_default=sa.text("1"), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("version >= 1", name=op.f("ck_products_version_positive")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_products")),
        sa.UniqueConstraint("partner_sku", name=op.f("uq_products_partner_sku")),
    )
    op.create_index(op.f("ix_products_product_id"), "products", ["product_id"], unique=False)
    op.create_table(
        "product_changes",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("partner_sku", sa.Text(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("change_type", sa.Text(), nullable=False),
        sa.Column("prev_fingerprint", sa.LargeBinary(), nullable=True),
        sa.Column("fingerprint", sa.LargeBinary(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "diff",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
        sa.Column("source", sa.Text(), nullable=False),
        sa.Column("source_ref", sa.Text(), nullable=False),
        sa.Column("observed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "(version = 1) = (change_type = 'CREATED')",
            name=op.f("ck_product_changes_created_is_first_version"),
        ),
        sa.CheckConstraint(
            "change_type IN ('CREATED', 'UPDATED')", name=op.f("ck_product_changes_change_type")
        ),
        sa.CheckConstraint(
            "source IN ('POLLING', 'WEBHOOK', 'EXCEL')", name=op.f("ck_product_changes_source")
        ),
        sa.CheckConstraint(
            "(version = 1) = (prev_fingerprint IS NULL)",
            name=op.f("ck_product_changes_first_version_has_no_prev"),
        ),
        sa.CheckConstraint(
            "prev_fingerprint IS DISTINCT FROM fingerprint",
            name=op.f("ck_product_changes_fingerprint_changed"),
        ),
        sa.CheckConstraint("version >= 1", name=op.f("ck_product_changes_version_positive")),
        sa.ForeignKeyConstraint(
            ["partner_sku"],
            ["products.partner_sku"],
            name=op.f("fk_product_changes_partner_sku_products"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_product_changes")),
        sa.UniqueConstraint("partner_sku", "version", name=op.f("uq_product_changes_partner_sku_version")),
    )
    op.create_index(op.f("ix_product_changes_recorded_at"), "product_changes", ["recorded_at"], unique=False)
    op.create_index(
        op.f("ix_product_changes_source_recorded_at"),
        "product_changes",
        ["source", "recorded_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_product_changes_source_recorded_at"), table_name="product_changes")
    op.drop_index(op.f("ix_product_changes_recorded_at"), table_name="product_changes")
    op.drop_table("product_changes")
    op.drop_index(op.f("ix_products_product_id"), table_name="products")
    op.drop_table("products")
    # ### end Alembic commands ###
