"""create vietful emulator schema

Revision ID: 0985b84c1738
Revises: 58085105cd6f
Create Date: 2026-09-29 07:11:10.672249

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "0985b84c1738"
down_revision: str | Sequence[str] | None = "58085105cd6f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Alembic does not create schemas; the emulator owns `vietful` (D12).
    op.execute("CREATE SCHEMA IF NOT EXISTS vietful")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mutations",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("product_id", sa.Integer(), nullable=False),
        sa.Column("partner_sku", sa.Text(), nullable=False),
        sa.Column("changed_fields", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("kind IN ('CREATED', 'UPDATED')", name=op.f("ck_mutations_kind")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mutations")),
        schema="vietful",
    )
    op.create_index(
        op.f("ix_mutations_partner_sku"), "mutations", ["partner_sku"], unique=False, schema="vietful"
    )
    op.create_table(
        "products",
        sa.Column("product_id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("sku", sa.Text(), nullable=False),
        sa.Column("partner_sku", sa.Text(), nullable=False),
        sa.Column("product_name", sa.Text(), nullable=True),
        sa.Column("asset_type", sa.Text(), nullable=True),
        sa.Column("has_serial", sa.Boolean(), nullable=True),
        sa.Column("has_expiration", sa.Boolean(), nullable=True),
        sa.Column("color", sa.Text(), nullable=True),
        sa.Column("size", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column(
            "units",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column(
            "categories",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("product_id", name=op.f("pk_products")),
        sa.UniqueConstraint("partner_sku", name=op.f("uq_products_partner_sku")),
        schema="vietful",
    )
    op.create_table(
        "settings",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("fault_mode", sa.Text(), server_default=sa.text("'ok'"), nullable=False),
        sa.Column("fault_latency_ms", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("fault_error_rate", sa.Float(), server_default=sa.text("0"), nullable=False),
        sa.Column("webhook_endpoint", sa.Text(), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "fault_mode IN ('ok', 'down', 'slow', 'flaky')", name=op.f("ck_settings_fault_mode")
        ),
        sa.CheckConstraint(
            "fault_error_rate >= 0 AND fault_error_rate <= 1", name=op.f("ck_settings_fault_error_rate")
        ),
        sa.CheckConstraint("id = 1", name=op.f("ck_settings_single_row")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_settings")),
        schema="vietful",
    )
    # ### end Alembic commands ###
    # The single settings row, with defaults (fault mode "ok", no webhook subscriber).
    op.execute("INSERT INTO vietful.settings (id) VALUES (1)")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("settings", schema="vietful")
    op.drop_table("products", schema="vietful")
    op.drop_index(op.f("ix_mutations_partner_sku"), table_name="mutations", schema="vietful")
    op.drop_table("mutations", schema="vietful")
    # ### end Alembic commands ###
    op.execute("DROP SCHEMA IF EXISTS vietful")
