"""emulator webhook callbacks

Revision ID: 67eeb373a7e9
Revises: 1e2338f24ff9
Create Date: 2026-09-29 08:59:24.383942

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "67eeb373a7e9"
down_revision: str | Sequence[str] | None = "1e2338f24ff9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "callbacks",
        sa.Column("id", sa.Integer(), sa.Identity(always=False), nullable=False),
        sa.Column("event_id", sa.Text(), nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("mutation_id", sa.Integer(), nullable=True),
        sa.Column("body", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'PENDING'"), nullable=False),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("deliveries", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column(
            "next_attempt_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.Column("last_status", sa.Integer(), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("delivered_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint("status IN ('PENDING', 'DELIVERED', 'FAILED')", name=op.f("ck_callbacks_status")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_callbacks")),
        sa.UniqueConstraint("event_id", name=op.f("uq_callbacks_event_id")),
        schema="vietful",
    )
    op.create_index(
        op.f("ix_callbacks_next_attempt_at"),
        "callbacks",
        ["next_attempt_at"],
        unique=False,
        schema="vietful",
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.add_column(
        "settings",
        sa.Column("callback_duplicate_rate", sa.Float(), server_default=sa.text("0"), nullable=False),
        schema="vietful",
    )
    op.add_column(
        "settings",
        sa.Column("callback_max_retries", sa.Integer(), server_default=sa.text("5"), nullable=False),
        schema="vietful",
    )
    op.add_column(
        "settings",
        sa.Column("callback_retry_delay_ms", sa.Integer(), server_default=sa.text("2000"), nullable=False),
        schema="vietful",
    )
    op.add_column(
        "settings",
        sa.Column("callback_concurrency", sa.Integer(), server_default=sa.text("4"), nullable=False),
        schema="vietful",
    )
    # ### end Alembic commands ###
    # Autogenerate does not compare CHECK constraints of existing tables.
    op.create_check_constraint(
        op.f("ck_settings_duplicate_rate"),
        "settings",
        "callback_duplicate_rate >= 0 AND callback_duplicate_rate <= 1",
        schema="vietful",
    )
    op.create_check_constraint(
        op.f("ck_settings_max_retries"),
        "settings",
        "callback_max_retries BETWEEN 0 AND 100",
        schema="vietful",
    )
    op.create_check_constraint(
        op.f("ck_settings_retry_delay_ms"),
        "settings",
        "callback_retry_delay_ms BETWEEN 0 AND 3600000",
        schema="vietful",
    )
    op.create_check_constraint(
        op.f("ck_settings_concurrency"),
        "settings",
        "callback_concurrency BETWEEN 1 AND 100",
        schema="vietful",
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint(op.f("ck_settings_duplicate_rate"), "settings", type_="check", schema="vietful")
    op.drop_constraint(op.f("ck_settings_max_retries"), "settings", type_="check", schema="vietful")
    op.drop_constraint(op.f("ck_settings_retry_delay_ms"), "settings", type_="check", schema="vietful")
    op.drop_constraint(op.f("ck_settings_concurrency"), "settings", type_="check", schema="vietful")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("settings", "callback_concurrency", schema="vietful")
    op.drop_column("settings", "callback_retry_delay_ms", schema="vietful")
    op.drop_column("settings", "callback_max_retries", schema="vietful")
    op.drop_column("settings", "callback_duplicate_rate", schema="vietful")
    op.drop_index(
        op.f("ix_callbacks_next_attempt_at"),
        table_name="callbacks",
        schema="vietful",
        postgresql_where=sa.text("status = 'PENDING'"),
    )
    op.drop_table("callbacks", schema="vietful")
    # ### end Alembic commands ###
