"""create poll_run and sync_config

Revision ID: 2fc4ba688033
Revises: 0985b84c1738
Create Date: 2026-09-29 07:31:16.767807

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2fc4ba688033"
down_revision: str | Sequence[str] | None = "0985b84c1738"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "poll_run",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("trigger", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'RUNNING'"), nullable=False),
        sa.Column("pages", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("items", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("created", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("updated", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("unchanged", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("stale", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("invalid", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('RUNNING', 'SUCCEEDED', 'FAILED', 'ABORTED')", name=op.f("ck_poll_run_status")
        ),
        sa.CheckConstraint("trigger IN ('SCHEDULE', 'MANUAL')", name=op.f("ck_poll_run_trigger")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_poll_run")),
    )
    op.create_index(op.f("ix_poll_run_started_at"), "poll_run", ["started_at"], unique=False)
    op.create_table(
        "sync_config",
        sa.Column("id", sa.Integer(), autoincrement=False, nullable=False),
        sa.Column("poll_enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("poll_interval_seconds", sa.Integer(), server_default=sa.text("30"), nullable=False),
        sa.Column("poll_page_size", sa.Integer(), server_default=sa.text("100"), nullable=False),
        sa.Column("http_connect_timeout_ms", sa.Integer(), server_default=sa.text("3000"), nullable=False),
        sa.Column("http_read_timeout_ms", sa.Integer(), server_default=sa.text("10000"), nullable=False),
        sa.Column("http_max_attempts", sa.Integer(), server_default=sa.text("3"), nullable=False),
        sa.Column("job_max_attempts", sa.Integer(), server_default=sa.text("5"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint(
            "http_connect_timeout_ms BETWEEN 100 AND 60000",
            name=op.f("ck_sync_config_http_connect_timeout_ms"),
        ),
        sa.CheckConstraint(
            "http_max_attempts BETWEEN 1 AND 10", name=op.f("ck_sync_config_http_max_attempts")
        ),
        sa.CheckConstraint(
            "http_read_timeout_ms BETWEEN 100 AND 300000", name=op.f("ck_sync_config_http_read_timeout_ms")
        ),
        sa.CheckConstraint("id = 1", name=op.f("ck_sync_config_single_row")),
        sa.CheckConstraint(
            "job_max_attempts BETWEEN 1 AND 100", name=op.f("ck_sync_config_job_max_attempts")
        ),
        sa.CheckConstraint(
            "poll_interval_seconds BETWEEN 5 AND 86400", name=op.f("ck_sync_config_poll_interval_seconds")
        ),
        sa.CheckConstraint("poll_page_size BETWEEN 1 AND 500", name=op.f("ck_sync_config_poll_page_size")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_sync_config")),
    )
    # ### end Alembic commands ###
    # The single config row with the defaults above (D9); edited at runtime, never re-created.
    op.execute("INSERT INTO sync_config (id) VALUES (1)")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("sync_config")
    op.drop_index(op.f("ix_poll_run_started_at"), table_name="poll_run")
    op.drop_table("poll_run")
    # ### end Alembic commands ###
