"""create inbox_event and job

Revision ID: 1e2338f24ff9
Revises: 2fc4ba688033
Create Date: 2026-09-29 08:33:45.382032

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "1e2338f24ff9"
down_revision: str | Sequence[str] | None = "2fc4ba688033"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "inbox_event",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("source", sa.Text(), server_default=sa.text("'vietful'"), nullable=False),
        sa.Column("event_id", sa.Text(), nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("body_sha256", sa.LargeBinary(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("event_ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("outcome", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("received_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "status IN ('PENDING', 'PROCESSED', 'IGNORED', 'DEAD')", name=op.f("ck_inbox_event_status")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inbox_event")),
        sa.UniqueConstraint("source", "event_id", name=op.f("uq_inbox_event_source_event_id")),
    )
    op.create_index(
        op.f("ix_inbox_event_status_received_at"), "inbox_event", ["status", "received_at"], unique=False
    )
    op.create_table(
        "job",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=True), nullable=False),
        sa.Column("kind", sa.Text(), nullable=False),
        sa.Column("ref_id", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), server_default=sa.text("'PENDING'"), nullable=False),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("run_after", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("locked_by", sa.Text(), nullable=True),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("kind IN ('webhook_event', 'poll_now')", name=op.f("ck_job_kind")),
        sa.CheckConstraint("status IN ('PENDING', 'RUNNING', 'DONE', 'DEAD')", name=op.f("ck_job_status")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job")),
        sa.UniqueConstraint("kind", "ref_id", name=op.f("uq_job_kind_ref_id")),
    )
    op.create_index(
        op.f("ix_job_run_after"),
        "job",
        ["run_after"],
        unique=False,
        postgresql_where=sa.text("status IN ('PENDING', 'RUNNING')"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_job_run_after"),
        table_name="job",
        postgresql_where=sa.text("status IN ('PENDING', 'RUNNING')"),
    )
    op.drop_table("job")
    op.drop_index(op.f("ix_inbox_event_status_received_at"), table_name="inbox_event")
    op.drop_table("inbox_event")
    # ### end Alembic commands ###
