"""Write `compose.env` for `docker compose up` with fresh random secrets (never committed, see .gitignore).

    python scripts/make_compose_env.py [--force]

The containerized stack has its own PostgreSQL, so none of these values are shared with local development.
"""

import argparse
import secrets
import sys
from pathlib import Path

TARGET = Path(__file__).resolve().parents[1] / "compose.env"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n\n")[0])
    parser.add_argument("--force", action="store_true", help="overwrite an existing compose.env")
    args = parser.parse_args()
    if TARGET.exists() and not args.force:
        print(f"{TARGET.name} already exists (use --force to replace it)")
        return 0
    password = secrets.token_urlsafe(24)
    TARGET.write_text(
        "\n".join(
            [
                "# Generated by scripts/make_compose_env.py — local secrets of the docker compose stack.",
                "POSTGRES_USER=cdms",
                f"POSTGRES_PASSWORD={password}",
                "DB_USER=cdms",
                f"DB_PASSWORD={password}",
                f"INVENTORY_API_TOKEN={secrets.token_urlsafe(24)}",
                f"WEBHOOK_SECRET={secrets.token_urlsafe(32)}",
                "",
            ]
        ),
        encoding="utf-8",
    )
    print(f"wrote {TARGET.name}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
